### ISSUE TITLE
Needs revision ahead of Matrix 1.6-2 release

### ISSUE THREAD

**Issue by dpmcsuss** [dpmcsuss/iGraphMatch#57]
Matrix 1.6-2 defines additional methods for the `%*%` operator
that mask your four methods

```
     `%*%`(x=<matrix_list>, y=<ANY>)
     `%*%`(x=<ANY>, y=<matrix_list>)
     `%*%`(x=<graphMatch>, y=<ANY>)
     `%*%`(x=<ANY>, y=<graphMatch>)

```
where `<ANY>` inherits from virtual class Matrix.  To ensure that your methods
continue to be dispatched, define four additional methods:
```

     `%*%`(x=<matrix_list>, y=<Matrix>)
     `%*%`(x=<Matrix>, y=<matrix_list>)
     `%*%`(x=<graphMatch>, y=<Matrix>)
     `%*%`(x=<Matrix>, y=<graphMatch>)
```

The new methods can be identical to the ones with `<ANY>` in the signature.

Please revise your package and test that it passes its checks under the latest
Matrix-devel, which you can install with
```
     install.packages("Matrix", repos = "http://r-forge.r-project.org/")
```

We anticipate releasing Matrix 1.6-2 in mid-October.

**Comment by jaganmn** [comment]
We intend to release Matrix 1.6-2 as early as Nov 3.  We've waited a bit longer to give rev. dep. maintainers more time to react.  I see that you've already patched the problems ~2 weeks ago, so I trust that you'll submit your update when ready.

**Comment by dpmcsuss** [comment]
Thanks, unfortunately, I'm still seeing an error from `irlba` on the Win-builder. You can see the error here https://win-builder.r-project.org/OXR7k7U8fm3f/00check.log
I'm not getting the error locally. I can try submitting to CRAN but I was hoping IRLBA might update.

**Comment by dpmcsuss** [comment]
The error is 
```
Error in irlba::irlba(a, rank) : 
  function 'as_cholmod_sparse' not provided by package 'Matrix'
```

**Comment by jaganmn** [comment]
It is a binary incompatibility problem on the win-builder machine.  **irlba** was installed under **Matrix** 1.6-1, but your **iGraphMatch** tarball was installed under **Matrix** 1.6-2.  1.6-2 is currently installed on the win-builder machine perhaps because I recently submitted a 1.6-2 tarball to be checked ... ?

You can reproduce by doing the same: install **Matrix** 1.6-1, install **irlba**, install **Matrix** 1.6-2, check your tarball.

All of which is to say that I don't think that CRAN will run into the same problem when you submit your update.  It is a peculiarity of the win-builder setup.

**Comment by jaganmn** [comment]
This is the first binary incompatible **Matrix** update in a while, so it's just bad luck ...

**Comment by dpmcsuss** [comment]
Thanks! I'll submit to CRAN very soon.
